/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package motorph_gui;

import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author amatibag
 */
public class AdminHome extends javax.swing.JFrame {
    private String loginName;
    

    /**
     * Creates new form AdminHome
     */
    public AdminHome(String username) {
        initComponents();
        setIconImage();
        
        // Set the login name based on username
        setLoginName(username);
        
        // Load the CSV data into the table
        loadCSVData();
    }

    // Method to set the login name label
    private void setLoginName(String username) {
        try (BufferedReader br = new BufferedReader(new FileReader("password.csv"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] data = line.split(",");
                String csvUsername = data[1];
                String firstName = data[4];  // 5th column (index 4) for first name
                String lastName = data[5];   // 6th column (index 5) for last name
                
                if (username.equals(csvUsername)) {
                    loginName = firstName + " " + lastName;
                    jLabelLoginName.setText(loginName);
                    return;
                }
            }
            JOptionPane.showMessageDialog(this, "Username not found in database.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    private void loadCSVData() {
        DefaultTableModel model = (DefaultTableModel) employeeTable.getModel();
        try (BufferedReader br = new BufferedReader(new FileReader("motorPHEmployeeList.csv"))) {
            String line;
            boolean isFirstRow = true;
            while ((line = br.readLine()) != null) {
                if (isFirstRow) {
                    isFirstRow = false; // Skip the header row
                    continue;
                }
                String[] data = line.split(",");
                if (data.length >= 10) {
                    String[] rowData = {
                        data[0],  // Employee Number
                        data[1],  // Last Name
                        data[2],  // First Name
                        data[6],  // SSS Number
                        data[7],  // Philhealth Number
                        data[8],  // TIN Number
                        data[9]   // Pag-ibig Number
                    };
                    model.addRow(rowData);
                }
            }
            // Set header font after loading data
            employeeTable.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 10));
        
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelWelcome = new javax.swing.JLabel();
        jLabelLoginName = new javax.swing.JLabel();
        logoutBTN = new javax.swing.JButton();
        jScrollPaneTable = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();
        jLeeNo = new javax.swing.JLabel();
        jLlastName = new javax.swing.JLabel();
        jLfirstName = new javax.swing.JLabel();
        jLbDay = new javax.swing.JLabel();
        jLaddress = new javax.swing.JLabel();
        jLphoneNo = new javax.swing.JLabel();
        jLSSS = new javax.swing.JLabel();
        jLPhilhealth = new javax.swing.JLabel();
        jLTIN = new javax.swing.JLabel();
        jLPagibig = new javax.swing.JLabel();
        jLStatus = new javax.swing.JLabel();
        jLPosition = new javax.swing.JLabel();
        jLSup = new javax.swing.JLabel();
        jLBasic = new javax.swing.JLabel();
        jLRice = new javax.swing.JLabel();
        jLphoneAllow = new javax.swing.JLabel();
        jLClothing = new javax.swing.JLabel();
        jLSemi = new javax.swing.JLabel();
        jLHourly = new javax.swing.JLabel();
        jTemployeeNo = new javax.swing.JTextField();
        jTlastName = new javax.swing.JTextField();
        jTfirstName = new javax.swing.JTextField();
        jTbirthday = new javax.swing.JTextField();
        jTaddress = new javax.swing.JTextField();
        jTphoneNo = new javax.swing.JTextField();
        jTsssNo = new javax.swing.JTextField();
        jTphilhealth = new javax.swing.JTextField();
        jTtin = new javax.swing.JTextField();
        jTpagibig = new javax.swing.JTextField();
        jTstatus = new javax.swing.JTextField();
        jTposition = new javax.swing.JTextField();
        jsupervisor = new javax.swing.JTextField();
        jTbasic = new javax.swing.JTextField();
        jTrice = new javax.swing.JTextField();
        jTphoneallow = new javax.swing.JTextField();
        jTclothing = new javax.swing.JTextField();
        jTsemi = new javax.swing.JTextField();
        jThourly = new javax.swing.JTextField();
        adminHomeBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Home Page");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelWelcome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelWelcome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelWelcome.setText("Welcome,");
        getContentPane().add(jLabelWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 60, 20));

        jLabelLoginName.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelLoginName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLoginName.setText("User Name Here");
        getContentPane().add(jLabelLoginName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 180, -1));

        logoutBTN.setBackground(new java.awt.Color(153, 39, 0));
        logoutBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logoutBTN.setForeground(new java.awt.Color(255, 255, 255));
        logoutBTN.setText("Log-out");
        logoutBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(60, 126, 114), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(210, 89, 51)));
        logoutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBTNActionPerformed(evt);
            }
        });
        getContentPane().add(logoutBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 130, 30));

        employeeTable.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        employeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee No.", "Last Name", "First Name", "SSS No.", "Philhealth No.", "TIN No.", "Pag-ibig No."
            }
        ));
        employeeTable.setGridColor(new java.awt.Color(60, 126, 114));
        employeeTable.setSelectionBackground(new java.awt.Color(210, 89, 51));
        jScrollPaneTable.setViewportView(employeeTable);

        getContentPane().add(jScrollPaneTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 600, 510));

        jLeeNo.setText("Employee Number");
        getContentPane().add(jLeeNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 125, -1, -1));

        jLlastName.setText("Last Name");
        getContentPane().add(jLlastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        jLfirstName.setText("First Name");
        getContentPane().add(jLfirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 175, -1, -1));

        jLbDay.setText("Birthday");
        getContentPane().add(jLbDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        jLaddress.setText("Address");
        getContentPane().add(jLaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 225, -1, -1));

        jLphoneNo.setText("Phone Number");
        getContentPane().add(jLphoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 285, -1, -1));

        jLSSS.setText("SSS Number");
        getContentPane().add(jLSSS, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        jLPhilhealth.setText("Philhealth Number");
        getContentPane().add(jLPhilhealth, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 335, -1, -1));

        jLTIN.setText("TIN Number");
        getContentPane().add(jLTIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, -1));

        jLPagibig.setText("Pag-ibig Number");
        getContentPane().add(jLPagibig, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 385, -1, -1));

        jLStatus.setText("Status");
        getContentPane().add(jLStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, -1, -1));

        jLPosition.setText("Position");
        getContentPane().add(jLPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 435, -1, -1));

        jLSup.setText("Immediate Supervisor");
        getContentPane().add(jLSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, -1, -1));

        jLBasic.setText("Basic Salary");
        getContentPane().add(jLBasic, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 485, -1, -1));

        jLRice.setText("Rice Subsidy");
        getContentPane().add(jLRice, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, -1, -1));

        jLphoneAllow.setText("Phone Allowance");
        getContentPane().add(jLphoneAllow, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 535, -1, -1));

        jLClothing.setText("Clothing Allowance");
        getContentPane().add(jLClothing, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 560, -1, -1));

        jLSemi.setText("Gross Semi-monthly Rate");
        getContentPane().add(jLSemi, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 585, -1, -1));

        jLHourly.setText("Hourly Rate");
        getContentPane().add(jLHourly, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 610, -1, -1));

        jTemployeeNo.setBackground(new java.awt.Color(255, 245, 206));
        jTemployeeNo.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jTemployeeNo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 175, 0), new java.awt.Color(255, 175, 0)));
        getContentPane().add(jTemployeeNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 122, 148, 22));

        jTlastName.setBackground(new java.awt.Color(255, 245, 206));
        jTlastName.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jTlastName.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 175, 0), new java.awt.Color(255, 175, 0)));
        getContentPane().add(jTlastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 147, 148, 22));

        jTfirstName.setBackground(new java.awt.Color(255, 245, 206));
        jTfirstName.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jTfirstName.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 175, 0), new java.awt.Color(255, 175, 0)));
        getContentPane().add(jTfirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 172, 148, 22));

        jTbirthday.setBackground(new java.awt.Color(255, 245, 206));
        jTbirthday.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jTbirthday.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 175, 0), new java.awt.Color(255, 175, 0)));
        getContentPane().add(jTbirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 197, 148, 22));

        jTaddress.setBackground(new java.awt.Color(255, 245, 206));
        jTaddress.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jTaddress.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 175, 0), new java.awt.Color(255, 175, 0)));
        getContentPane().add(jTaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 222, 220, 59));

        jTphoneNo.setBackground(new java.awt.Color(255, 245, 206));
        jTphoneNo.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jTphoneNo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 175, 0), new java.awt.Color(255, 175, 0)));
        getContentPane().add(jTphoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 282, 148, 22));

        jTsssNo.setBackground(new java.awt.Color(255, 245, 206));
        jTsssNo.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jTsssNo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 175, 0), new java.awt.Color(255, 175, 0)));
        getContentPane().add(jTsssNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 307, 148, 22));

        jTphilhealth.setBackground(new java.awt.Color(255, 245, 206));
        jTphilhealth.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jTphilhealth.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 175, 0), new java.awt.Color(255, 175, 0)));
        getContentPane().add(jTphilhealth, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 332, 148, 22));

        jTtin.setBackground(new java.awt.Color(255, 245, 206));
        jTtin.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jTtin.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 175, 0), new java.awt.Color(255, 175, 0)));
        getContentPane().add(jTtin, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 357, 148, 22));

        jTpagibig.setBackground(new java.awt.Color(255, 245, 206));
        jTpagibig.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jTpagibig.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 175, 0), new java.awt.Color(255, 175, 0)));
        getContentPane().add(jTpagibig, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 382, 148, 22));

        jTstatus.setBackground(new java.awt.Color(255, 245, 206));
        jTstatus.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jTstatus.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 175, 0), new java.awt.Color(255, 175, 0)));
        getContentPane().add(jTstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 407, 148, 22));

        jTposition.setBackground(new java.awt.Color(255, 245, 206));
        jTposition.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jTposition.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 175, 0), new java.awt.Color(255, 175, 0)));
        getContentPane().add(jTposition, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 432, 148, 22));

        jsupervisor.setBackground(new java.awt.Color(255, 245, 206));
        jsupervisor.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jsupervisor.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 175, 0), new java.awt.Color(255, 175, 0)));
        getContentPane().add(jsupervisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 457, 148, 22));

        jTbasic.setBackground(new java.awt.Color(255, 245, 206));
        jTbasic.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jTbasic.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 175, 0), new java.awt.Color(255, 175, 0)));
        getContentPane().add(jTbasic, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 482, 120, 22));

        jTrice.setBackground(new java.awt.Color(255, 245, 206));
        jTrice.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jTrice.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 175, 0), new java.awt.Color(255, 175, 0)));
        getContentPane().add(jTrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 507, 120, 22));

        jTphoneallow.setBackground(new java.awt.Color(255, 245, 206));
        jTphoneallow.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jTphoneallow.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 175, 0), new java.awt.Color(255, 175, 0)));
        getContentPane().add(jTphoneallow, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 532, 120, 22));

        jTclothing.setBackground(new java.awt.Color(255, 245, 206));
        jTclothing.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jTclothing.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 175, 0), new java.awt.Color(255, 175, 0)));
        getContentPane().add(jTclothing, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 557, 120, 22));

        jTsemi.setBackground(new java.awt.Color(255, 245, 206));
        jTsemi.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jTsemi.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 175, 0), new java.awt.Color(255, 175, 0)));
        getContentPane().add(jTsemi, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 582, 120, 22));

        jThourly.setBackground(new java.awt.Color(255, 245, 206));
        jThourly.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jThourly.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 175, 0), new java.awt.Color(255, 175, 0)));
        getContentPane().add(jThourly, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 607, 120, 22));

        adminHomeBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/motorph_gui/AdminHome.jpg"))); // NOI18N
        getContentPane().add(adminHomeBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBTNActionPerformed
        // Close the current frame (AdminHome or UserHome)
    dispose();

    // Open the LoginPage
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new LoginPage().setVisible(true);
        }
    });
    }//GEN-LAST:event_logoutBTNActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AdminHome("username").setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminHomeBG;
    private javax.swing.JTable employeeTable;
    private javax.swing.JLabel jLBasic;
    private javax.swing.JLabel jLClothing;
    private javax.swing.JLabel jLHourly;
    private javax.swing.JLabel jLPagibig;
    private javax.swing.JLabel jLPhilhealth;
    private javax.swing.JLabel jLPosition;
    private javax.swing.JLabel jLRice;
    private javax.swing.JLabel jLSSS;
    private javax.swing.JLabel jLSemi;
    private javax.swing.JLabel jLStatus;
    private javax.swing.JLabel jLSup;
    private javax.swing.JLabel jLTIN;
    private javax.swing.JLabel jLabelLoginName;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JLabel jLaddress;
    private javax.swing.JLabel jLbDay;
    private javax.swing.JLabel jLeeNo;
    private javax.swing.JLabel jLfirstName;
    private javax.swing.JLabel jLlastName;
    private javax.swing.JLabel jLphoneAllow;
    private javax.swing.JLabel jLphoneNo;
    private javax.swing.JScrollPane jScrollPaneTable;
    private javax.swing.JTextField jTaddress;
    private javax.swing.JTextField jTbasic;
    private javax.swing.JTextField jTbirthday;
    private javax.swing.JTextField jTclothing;
    private javax.swing.JTextField jTemployeeNo;
    private javax.swing.JTextField jTfirstName;
    private javax.swing.JTextField jThourly;
    private javax.swing.JTextField jTlastName;
    private javax.swing.JTextField jTpagibig;
    private javax.swing.JTextField jTphilhealth;
    private javax.swing.JTextField jTphoneNo;
    private javax.swing.JTextField jTphoneallow;
    private javax.swing.JTextField jTposition;
    private javax.swing.JTextField jTrice;
    private javax.swing.JTextField jTsemi;
    private javax.swing.JTextField jTsssNo;
    private javax.swing.JTextField jTstatus;
    private javax.swing.JTextField jTtin;
    private javax.swing.JTextField jsupervisor;
    private javax.swing.JButton logoutBTN;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Logo.jpg")));
    }
}
